In [1]:
import pandas as pd
import numpy as np
import ast
import pickle
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import multirecording_spikeanalysis_edit4 as spike

# It takes several steps to create the timestamp_dicts, refer to Ephys_Analysis_Notebook to create
timestamp_dicts = pickle.load(open('timestamp_dicts.pkl', 'rb'))

# Construct the path in a platform-independent way (HiPerGator or Windows)
ephys_path = Path('.') / 'export' / 'updated_phys' / 'test'

ephys_data = spike.EphysRecordingCollection(str(ephys_path))

<class 'numpy.ndarray'>
20230612_101430_standard_comp_to_training_D1_subj_1-3_t3b3L_box2_merged.rec
<class 'numpy.ndarray'>
20230617_115521_standard_comp_to_omission_D1_subj_1-1_t1b3L_box1_merged.rec
<class 'numpy.ndarray'>
Unit 92 is unsorted & has 2494 spikes
Unit 92 will be deleted
20230622_110832_standard_comp_to_both_rewarded_D1_subj_1-1_t1b3L_box1_merged.rec
<class 'numpy.ndarray'>
Unit 103 is unsorted & has 512 spikes
Unit 103 will be deleted
20230622_110832_standard_comp_to_both_rewarded_D1_subj_1-2_t3b3L_box1_merged.rec
Please assign event dictionaries to each recording
as recording.event_dict
event_dict = {event name(str): np.array[[start(ms), stop(ms)]...]
Please assign subjects to each recording as recording.subject

In [2]:
for recording in ephys_data.collection.keys():
    # Check if the recording key (without everything after subject #) is in timestamp_dicts
    start_pos = recording.find('subj_')
    # Add the length of 'subj_' and 3 additional characters to include after 'subj_'
    end_pos = start_pos + len('subj_') + 3
    # Slice the recording key to get everything up to and including the subject identifier plus three characters
    recording_key_without_suffix = recording[:end_pos]
    if recording_key_without_suffix in timestamp_dicts:
        # Assign the corresponding timestamp_dicts dictionary to event_dict
        ephys_data.collection[recording].event_dict = timestamp_dicts[recording_key_without_suffix]
        
        # Extract the subject from the recording key
        start = recording.find('subj_') + 5  # Start index after 'subj_'
        subject = recording[start:start+3]
        
        # Assign the extracted subject
        ephys_data.collection[recording].subject = subject
        
spike_analysis = spike.SpikeAnalysis_MultiRecording(ephys_data, timebin = 100, ignore_freq = 0.5)

All set to analyze

In [3]:
event_df = spike_analysis.create_spiketrain_df()

event_df

,Recording,Event name,Event number,Unit number,bin_1,bin_2,bin_3,bin_4,bin_5,bin_6,...,bin_92,bin_93,bin_94,bin_95,bin_96,bin_97,bin_98,bin_99,bin_100,bin_101
0,20230612_101430_standard_comp_to_training_D1_s...,rewarded,1,85,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,20230612_101430_standard_comp_to_training_D1_s...,rewarded,2,85,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,20230612_101430_standard_comp_to_training_D1_s...,rewarded,3,85,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,20230612_101430_standard_comp_to_training_D1_s...,rewarded,4,85,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,20230612_101430_standard_comp_to_training_D1_s...,rewarded,5,85,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2712,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,16,15,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2713,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,15,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2714,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,18,15,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2715,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,19,15,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2716,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,20,15,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [8]:
df101 = event_df[event_df['bin_101'] == True]

In [9]:
df101

,Recording,Event name,Event number,Unit number,bin_1,bin_2,bin_3,bin_4,bin_5,bin_6,...,bin_92,bin_93,bin_94,bin_95,bin_96,bin_97,bin_98,bin_99,bin_100,bin_101
1533,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,15,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0
2253,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,45,1.0,0.0,2.0,1.0,2.0,1.0,...,1.0,2.0,0.0,1.0,4.0,1.0,1.0,0.0,1.0,1.0
2273,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,33,3.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,1.0,1.0
2293,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,109,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2313,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,76,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
2373,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,44,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0
2413,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,48,1.0,2.0,1.0,1.0,2.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2593,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,59,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2613,20230622_110832_standard_comp_to_both_rewarded...,both_rewarded,17,51,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0

In [11]:
recordings = spike_analysis.ephyscollection.collection
recording_name = '20230622_110832_standard_comp_to_both_rewarded_D1_subj_1-1_t1b3L_box1_merged.rec'
recording1 = recordings.get(recording_name)
recording1.event_dict['both_rewarded']

array([[2036584, 2046584],
       [2096585, 2106585],
       [2151586, 2161586],
       [2216587, 2226587],
       [2271587, 2281587],
       [2321588, 2331588],
       [2371589, 2381589],
       [2476590, 2486590],
       [2596591, 2606592],
       [2716593, 2726593],
       [2826594, 2836595],
       [2911595, 2921596],
       [3031597, 3041597],
       [3091598, 3101598],
       [3156599, 3166599],
       [3216599, 3226600],
       [3291600, 3301601],
       [3391602, 3401602],
       [3486603, 3496603],
       [3536603, 3546604]], dtype=int64)

In [12]:
3216599 / 100

32165.99

In [13]:
3226600 / 100

32266.0

In [14]:
np.ceil(3216599 / 100)

32166.0

In [15]:
np.ceil(3226600 / 100)

32266.0

In [17]:
print(np.ceil(3216599 / 100))
print(np.ceil(3226600 / 100))
print(np.ceil(3291600 / 100))
print(np.ceil(3301601 / 100))
print(np.ceil(3391602 / 100))
print(np.ceil(3401602 / 100))

32166.0
32266.0
32916.0
33017.0
33917.0
34017.0